{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-probably
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/probably_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/probably/probably_{{ version }}.tar.gz
  sha256: 1651787d316986ac28634d0f0c833419ad33e1f66e964d3872561c3b4c2668b2

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-butcher
    - r-cli
    - r-dplyr >=1.1.0
    - r-furrr
    - r-generics >=0.1.3
    - r-ggplot2
    - r-hardhat
    - r-pillar
    - r-purrr
    - r-rlang >=1.0.4
    - r-tidyr >=1.3.0
    - r-tidyselect >=1.1.2
    - r-tune >=1.1.0
    - r-vctrs >=0.4.1
    - r-withr
    - r-workflows
    - r-yardstick >1.0.0
  run:
    - r-base
    - r-butcher
    - r-cli
    - r-dplyr >=1.1.0
    - r-furrr
    - r-generics >=0.1.3
    - r-ggplot2
    - r-hardhat
    - r-pillar
    - r-purrr
    - r-rlang >=1.0.4
    - r-tidyr >=1.3.0
    - r-tidyselect >=1.1.2
    - r-tune >=1.1.0
    - r-vctrs >=0.4.1
    - r-withr
    - r-workflows
    - r-yardstick >1.0.0

test:
  commands:
    - $R -e "library('probably')"           # [not win]
    - "\"%R%\" -e \"library('probably')\""  # [win]

about:
  home: https://github.com/tidymodels/probably/
  license: MIT
  summary: "Models can be improved by post-processing class probabilities, by: recalibration, conversion to hard probabilities, assessment of equivocal zones, and other activities. 'probably' contains tools for conducting these operations. "
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: probably
# Version: 0.0.2
# Title: Tools for Post-Processing Class Probability Estimates
# Description: Models can be improved by post-processing class probabilities, by: recalibration, conversion to hard probabilities, assessment of equivocal zones, and other activities. 'probably' contains tools for conducting these operations.
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Davis", "Vaughan", , "davis@rstudio.com", c("aut")), person("RStudio", role = "cph"))
# Maintainer: Max Kuhn <max@rstudio.com>
# URL: https://github.com/tidymodels/probably/
# BugReports: https://github.com/tidymodels/probably/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Imports: dplyr, generics, rlang, tidyselect, vctrs, yardstick
# Suggests: covr, ggplot2, knitr, parsnip, rmarkdown, rsample, testthat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-07 17:24:18 UTC; davis
# Author: Max Kuhn [aut, cre], Davis Vaughan [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2019-03-07 17:40:08 UTC
