{% set version = "0.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-probably
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/probably_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/probably/probably_{{ version }}.tar.gz
  sha256: b44c282e9dda03e5db12c9604048cbc6dbcfab02960d5762dda6ad5440718fd4

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-dplyr
    - r-generics
    - r-rlang >=0.4.0
    - r-tidyselect
    - r-vctrs >=0.2.0
    - r-yardstick
  run:
    - r-base
    - r-dplyr
    - r-generics
    - r-rlang >=0.4.0
    - r-tidyselect
    - r-vctrs >=0.2.0
    - r-yardstick

test:
  commands:
    - $R -e "library('probably')"           # [not win]
    - "\"%R%\" -e \"library('probably')\""  # [win]

about:
  home: https://github.com/tidymodels/probably/
  license: GPL-2.0-only
  summary: "Models can be improved by post-processing class probabilities, by: recalibration, conversion to hard probabilities, assessment of equivocal zones, and other activities. 'probably' contains tools for conducting these operations. "
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: probably
# Version: 0.0.2
# Title: Tools for Post-Processing Class Probability Estimates
# Description: Models can be improved by post-processing class probabilities, by: recalibration, conversion to hard probabilities, assessment of equivocal zones, and other activities. 'probably' contains tools for conducting these operations.
# Authors@R: c( person("Max", "Kuhn", , "max@rstudio.com", c("aut", "cre")), person("Davis", "Vaughan", , "davis@rstudio.com", c("aut")), person("RStudio", role = "cph"))
# Maintainer: Max Kuhn <max@rstudio.com>
# URL: https://github.com/tidymodels/probably/
# BugReports: https://github.com/tidymodels/probably/issues
# License: GPL-2
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 6.1.1
# Depends: R (>= 2.10)
# Imports: dplyr, generics, rlang, tidyselect, vctrs, yardstick
# Suggests: covr, ggplot2, knitr, parsnip, rmarkdown, rsample, testthat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-03-07 17:24:18 UTC; davis
# Author: Max Kuhn [aut, cre], Davis Vaughan [aut], RStudio [cph]
# Repository: CRAN
# Date/Publication: 2019-03-07 17:40:08 UTC
