appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NBB4YS6ZdfBECguiVouQk5ZJsPaE6U7x45Y7mLs2dpYRdl7ww0DQOsV1aq8jHZ1tcujQP/fiq+aeXmQksX04l717DLGUmChiHTQXixz7Tx8LFXRtTCsVywBOv2sj9bo9bS1GOfHb4PJxCRV7PD3LygGwwplwoQzBo4zr0GeAglwZcERCXnpecBJ8xvEUYeGvZyu0MMVXaLpTC3tNYoRBe+j5lP2NsQxxodWy18LrfmeNUyQMF/r3gRTK2u07K72GrCAkFnLOaLX7t5NAzYPvl6JldFvV05eP0R3y4PJV3NxboENjsOkyCnZGIAsdgfdCEBAHUEe0N0LSgB9O3JacO0l2vQqNaWOq+shvgNJHs2s115rg7CprDOVZxmoSa6AqSoY3TwgXGH5JYcCON7vz2hDB6Op66b2KsM82HWwxqtUqiIQ54OqxPwXp1HUOHPl/GVkO8HTL67KpwtHjMl9S5vmhNFXKYvQnwlRZ69KlulnTtI9Z5T31y4t6Aq9rmGFIOBefmq41lFAv0c6MUME7a4eFUVoFXapGBmKKJ/KqNp21kUvo4lU0cAyw87PSOMYMmTtVsODEkCEqsoyNodRGdqOyj5/UihILYdg5fwu6xPuCA1ZlphodOUMOdGZc0DGViTvPmBQLvuSxJ9FBwIxkoFoaDS9akjgLbcCHt/L35tw=}
