travis:
  secure:
    BINSTAR_TOKEN: oycJNquagsVJGt3/Ud7zU9XKUHSu0taTf3UZpDlHYWrxndXaCK+fGKgIOTzAqeymUoCaJtcz8vYjayS8QrkgkG3DBInExt0l9DMVqM9trs2xWCi1NCpM1iu6AM/0FXChy1Hhvn5VWyudHE1s7fTqrxtr28TJoVoV4J9DXj3wlkbKKQpBFRfv5bpDMUSVlh/YXfzjjwmgEzno8Gx/BcUPBO2ebuOvvxrJueAVNoJv/Hfj4QQxWk2xKktUEUz1ooSJ1V9p4F4VffzSuD9nPBnbxkMXaw5hF+3LnV8l2VHwIu46Hb4iAeetbBjF+UiEQUELPrAVZa7hkG9rH0TlDAmFI+Ny6LFSIDsJzvoPYgNIAshet8F3LnVcx/H6qdqLUtogENkGu5qHhgMvXutKbmD9xwoe7IMadCMHq6vBanNrYpadNPftIGQlne9DT5YqzNc+9nZKBdHlaCRpD5gsdzj50RGi55mGaAursjCgTPQjLNgK02UO5cktBmeWfH9Bwcbfhu1Qds31nNO10aT+egxguOMtRlKdd4kYbFx0yZFenLhoOHr2tpSLGPhY88zZXa3DgTvcyN2q7p6Fqh7TM97tpDDLD5Z2Fwz767TQO7dEINuNqw2tXCRzLKGJ2dP7d6St2f9Ml9uN1GtoUSIIacvpG0QFgcBzOMViIhNkyZ/hgzM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
